ktor:
    application:
        modules:
            - pers.show.ApplicationKt.module
    deployment:
        port: 8080
postgres:
  url: "jdbc:postgresql://127.0.0.1:5432/postgres"
  user: postgres
  password: root