ktor:
    application:
        modules:
            - pers.show.ApplicationKt.module
    deployment:
        port: 8080
postgres:
  url: ${DATABASE_URL}
  port: ${PGPORT}
  user: ${PGUSER}
  password: ${PGPASSWORD}